//
//  QuotesExtension.swift
//  YiGe
//
//  扩展名言集合 - 600句完整版
//  包含：古诗词、日本哲语、欧美名言、电影台词等
//

import Foundation

extension QuotesManager {
    // 重写 getExtendedQuotes 方法，返回扩展名言
    static func getExtendedQuotes() -> [Quote] {
        return extendedTimeQuotes 
            + extendedLifeQuotes 
            + extendedPoetryQuotes 
            + extendedJapaneseQuotes 
            + extendedWesternQuotes 
            + extendedMovieQuotes
            + extendedFrenchQuotes
            + extendedLatinQuotes
    }
    
    // 时间相关名言
    private static var extendedTimeQuotes: [Quote] {
        [
            Quote(text: "时间是最公平的，给每个人都是24小时；时间也是最不公平的，给每个人都不是24小时。", source: "未知", category: .time),
            Quote(text: "时间就像海绵里的水，只要愿挤，总还是有的。", source: "鲁迅", category: .time),
            Quote(text: "时间就是生命，时间就是速度，时间就是力量。", source: "郭沫若", category: .time),
            Quote(text: "逝者如斯夫，不舍昼夜。", source: "孔子", category: .time),
            Quote(text: "时间会刺破青春表面的彩饰，会在美人的额上掘深沟浅槽。", source: "莎士比亚", category: .time, originalText: "Time doth transfix the flourish set on youth", originalLanguage: "en"),
            Quote(text: "时间是最伟大的治愈师。", source: "未知", category: .time),
            Quote(text: "时间带走一切，长年累月会把你的名字、外貌、性格、命运都改变。", source: "柏拉图", category: .time),
            Quote(text: "时间是一个伟大的作者，它会给每个人写出完美的结局来。", source: "卓别林", category: .time),
            Quote(text: "时间，每天得到的都是二十四小时，可是一天的时间给勤勉的人带来智慧和力量，给懒散的人只留下一片悔恨。", source: "鲁迅", category: .time),
            Quote(text: "时间就是金钱。", source: "富兰克林", category: .time, originalText: "Time is money", originalLanguage: "en"),
        ]
    }
    
    // 生活相关名言
    private static var extendedLifeQuotes: [Quote] {
        [
            Quote(text: "生活就像海洋，只有意志坚强的人，才能到达彼岸。", source: "马克思", category: .life),
            Quote(text: "生活不是等待暴风雨过去，而是要学会在雨中跳舞。", source: "未知", category: .life),
            Quote(text: "生活就像一面镜子，你对它笑，它就对你笑；你对它哭，它也对你哭。", source: "未知", category: .life),
            Quote(text: "生活不是缺少美，而是缺少发现美的眼睛。", source: "罗丹", category: .life),
            Quote(text: "生活就像骑自行车，想保持平衡就得往前走。", source: "爱因斯坦", category: .life),
            Quote(text: "生活是一面镜子，你笑它也笑，你哭它也哭。", source: "未知", category: .life),
            Quote(text: "生活不是单行线，一条路走不通，你可以转弯。", source: "未知", category: .life),
            Quote(text: "生活就像一杯茶，不会苦一辈子，但总会苦一阵子。", source: "未知", category: .life),
            Quote(text: "生活不是等待风暴过去，而是学会在雨中翩翩起舞。", source: "未知", category: .life),
            Quote(text: "生活就像一本书，愚者匆匆翻过，智者细细阅读。", source: "未知", category: .life),
        ]
    }
    
    // 扩展古诗词（补充至300条）
    private static var extendedPoetryQuotes: [Quote] {
        [
            // 唐诗
            Quote(text: "山重水复疑无路，柳暗花明又一村。", source: "陆游《游山西村》", category: .poetry),
            Quote(text: "问渠那得清如许，为有源头活水来。", source: "朱熹《观书有感》", category: .poetry),
            Quote(text: "不识庐山真面目，只缘身在此山中。", source: "苏轼《题西林壁》", category: .poetry),
            Quote(text: "欲把西湖比西子，淡妆浓抹总相宜。", source: "苏轼《饮湖上初晴后雨》", category: .poetry),
            Quote(text: "竹外桃花三两枝，春江水暖鸭先知。", source: "苏轼《惠崇春江晚景》", category: .poetry),
            Quote(text: "人有悲欢离合，月有阴晴圆缺，此事古难全。", source: "苏轼《水调歌头》", category: .poetry),
            Quote(text: "大江东去，浪淘尽，千古风流人物。", source: "苏轼《念奴娇·赤壁怀古》", category: .poetry),
            Quote(text: "十年生死两茫茫，不思量，自难忘。", source: "苏轼《江城子》", category: .poetry),
            Quote(text: "会挽雕弓如满月，西北望，射天狼。", source: "苏轼《江城子·密州出猎》", category: .poetry),
            Quote(text: "但愿人长久，千里共婵娟。", source: "苏轼《水调歌头》", category: .poetry),
            Quote(text: "两情若是久长时，又岂在朝朝暮暮。", source: "秦观《鹊桥仙》", category: .poetry),
            Quote(text: "众里寻他千百度，蓦然回首，那人却在，灯火阑珊处。", source: "辛弃疾《青玉案·元夕》", category: .poetry),
            Quote(text: "醉里挑灯看剑，梦回吹角连营。", source: "辛弃疾《破阵子》", category: .poetry),
            Quote(text: "了却君王天下事，赢得生前身后名。", source: "辛弃疾《破阵子》", category: .poetry),
            Quote(text: "青山遮不住，毕竟东流去。", source: "辛弃疾《菩萨蛮》", category: .poetry),
            Quote(text: "少年不识愁滋味，爱上层楼。", source: "辛弃疾《丑奴儿》", category: .poetry),
            Quote(text: "衣带渐宽终不悔，为伊消得人憔悴。", source: "柳永《蝶恋花》", category: .poetry),
            Quote(text: "多情自古伤离别，更那堪，冷落清秋节。", source: "柳永《雨霖铃》", category: .poetry),
            Quote(text: "今宵酒醒何处？杨柳岸，晓风残月。", source: "柳永《雨霖铃》", category: .poetry),
            Quote(text: "问君能有几多愁？恰似一江春水向东流。", source: "李煜《虞美人》", category: .poetry),
            Quote(text: "剪不断，理还乱，是离愁。", source: "李煜《相见欢》", category: .poetry),
            Quote(text: "无言独上西楼，月如钩。", source: "李煜《相见欢》", category: .poetry),
            Quote(text: "春花秋月何时了？往事知多少。", source: "李煜《虞美人》", category: .poetry),
            Quote(text: "落红不是无情物，化作春泥更护花。", source: "龚自珍《己亥杂诗》", category: .poetry),
            Quote(text: "我劝天公重抖擞，不拘一格降人才。", source: "龚自珍《己亥杂诗》", category: .poetry),
            Quote(text: "山不在高，有仙则名。水不在深，有龙则灵。", source: "刘禹锡《陋室铭》", category: .poetry),
            Quote(text: "沉舟侧畔千帆过，病树前头万木春。", source: "刘禹锡《酬乐天扬州初逢席上见赠》", category: .poetry),
            Quote(text: "旧时王谢堂前燕，飞入寻常百姓家。", source: "刘禹锡《乌衣巷》", category: .poetry),
            Quote(text: "东边日出西边雨，道是无晴却有晴。", source: "刘禹锡《竹枝词》", category: .poetry),
            Quote(text: "晴空一鹤排云上，便引诗情到碧霄。", source: "刘禹锡《秋词》", category: .poetry),
            Quote(text: "曾经沧海难为水，除却巫山不是云。", source: "元稹《离思》", category: .poetry),
            Quote(text: "取次花丛懒回顾，半缘修道半缘君。", source: "元稹《离思》", category: .poetry),
            Quote(text: "此情可待成追忆，只是当时已惘然。", source: "李商隐《锦瑟》", category: .poetry),
            Quote(text: "春蚕到死丝方尽，蜡炬成灰泪始干。", source: "李商隐《无题》", category: .poetry),
            Quote(text: "身无彩凤双飞翼，心有灵犀一点通。", source: "李商隐《无题》", category: .poetry),
            Quote(text: "相见时难别亦难，东风无力百花残。", source: "李商隐《无题》", category: .poetry),
            Quote(text: "夕阳无限好，只是近黄昏。", source: "李商隐《登乐游原》", category: .poetry),
            Quote(text: "何当共剪西窗烛，却话巴山夜雨时。", source: "李商隐《夜雨寄北》", category: .poetry),
            Quote(text: "商女不知亡国恨，隔江犹唱后庭花。", source: "杜牧《泊秦淮》", category: .poetry),
            Quote(text: "停车坐爱枫林晚，霜叶红于二月花。", source: "杜牧《山行》", category: .poetry),
            Quote(text: "清明时节雨纷纷，路上行人欲断魂。", source: "杜牧《清明》", category: .poetry),
            Quote(text: "一骑红尘妃子笑，无人知是荔枝来。", source: "杜牧《过华清宫》", category: .poetry),
            Quote(text: "春风十里扬州路，卷上珠帘总不如。", source: "杜牧《赠别》", category: .poetry),
            Quote(text: "二十四桥明月夜，玉人何处教吹箫。", source: "杜牧《寄扬州韩绰判官》", category: .poetry),
            Quote(text: "南朝四百八十寺，多少楼台烟雨中。", source: "杜牧《江南春》", category: .poetry),
            Quote(text: "劝君更尽一杯酒，西出阳关无故人。", source: "王维《送元二使安西》", category: .poetry),
            Quote(text: "君自故乡来，应知故乡事。", source: "王维《杂诗》", category: .poetry),
            Quote(text: "江流天地外，山色有无中。", source: "王维《汉江临眺》", category: .poetry),
            Quote(text: "但去莫复问，白云无尽时。", source: "王维《送别》", category: .poetry),
            Quote(text: "长风破浪会有时，直挂云帆济沧海。", source: "李白《行路难》", category: .poetry),
            Quote(text: "天生我材必有用，千金散尽还复来。", source: "李白《将进酒》", category: .poetry),
            Quote(text: "人生得意须尽欢，莫使金樽空对月。", source: "李白《将进酒》", category: .poetry),
            Quote(text: "抽刀断水水更流，举杯消愁愁更愁。", source: "李白《宣州谢脁楼饯别校书叔云》", category: .poetry),
            Quote(text: "仰天大笑出门去，我辈岂是蓬蒿人。", source: "李白《南陵别儿童入京》", category: .poetry),
            Quote(text: "安能摧眉折腰事权贵，使我不得开心颜。", source: "李白《梦游天姥吟留别》", category: .poetry),
            Quote(text: "飞流直下三千尺，疑是银河落九天。", source: "李白《望庐山瀑布》", category: .poetry),
            Quote(text: "孤帆远影碧空尽，唯见长江天际流。", source: "李白《黄鹤楼送孟浩然之广陵》", category: .poetry),
            Quote(text: "桃花潭水深千尺，不及汪伦送我情。", source: "李白《赠汪伦》", category: .poetry),
            Quote(text: "两岸猿声啼不住，轻舟已过万重山。", source: "李白《早发白帝城》", category: .poetry),
            Quote(text: "今人不见古时月，今月曾经照古人。", source: "李白《把酒问月》", category: .poetry),
            Quote(text: "云想衣裳花想容，春风拂槛露华浓。", source: "李白《清平调》", category: .poetry),
            Quote(text: "一夫当关，万夫莫开。", source: "李白《蜀道难》", category: .poetry),
            Quote(text: "蜀道之难，难于上青天。", source: "李白《蜀道难》", category: .poetry),
            Quote(text: "感时花溅泪，恨别鸟惊心。", source: "杜甫《春望》", category: .poetry),
            Quote(text: "烽火连三月，家书抵万金。", source: "杜甫《春望》", category: .poetry),
            Quote(text: "安得广厦千万间，大庇天下寒士俱欢颜。", source: "杜甫《茅屋为秋风所破歌》", category: .poetry),
            Quote(text: "无边落木萧萧下，不尽长江滚滚来。", source: "杜甫《登高》", category: .poetry),
            Quote(text: "出师未捷身先死，长使英雄泪满襟。", source: "杜甫《蜀相》", category: .poetry),
            Quote(text: "正是江南好风景，落花时节又逢君。", source: "杜甫《江南逢李龟年》", category: .poetry),
            Quote(text: "两个黄鹂鸣翠柳，一行白鹭上青天。", source: "杜甫《绝句》", category: .poetry),
            Quote(text: "窗含西岭千秋雪，门泊东吴万里船。", source: "杜甫《绝句》", category: .poetry),
            Quote(text: "好雨知时节，当春乃发生。", source: "杜甫《春夜喜雨》", category: .poetry),
            Quote(text: "随风潜入夜，润物细无声。", source: "杜甫《春夜喜雨》", category: .poetry),
            Quote(text: "露从今夜白，月是故乡明。", source: "杜甫《月夜忆舍弟》", category: .poetry),
            Quote(text: "星垂平野阔，月涌大江流。", source: "杜甫《旅夜书怀》", category: .poetry),
            Quote(text: "读书破万卷，下笔如有神。", source: "杜甫《奉赠韦左丞丈二十二韵》", category: .poetry),
            Quote(text: "野火烧不尽，春风吹又生。", source: "白居易《赋得古原草送别》", category: .poetry),
            Quote(text: "同是天涯沦落人，相逢何必曾相识。", source: "白居易《琵琶行》", category: .poetry),
            Quote(text: "别有幽愁暗恨生，此时无声胜有声。", source: "白居易《琵琶行》", category: .poetry),
            Quote(text: "回眸一笑百媚生，六宫粉黛无颜色。", source: "白居易《长恨歌》", category: .poetry),
            Quote(text: "天长地久有时尽，此恨绵绵无绝期。", source: "白居易《长恨歌》", category: .poetry),
            Quote(text: "上穷碧落下黄泉，两处茫茫皆不见。", source: "白居易《长恨歌》", category: .poetry),
            Quote(text: "忽如一夜春风来，千树万树梨花开。", source: "岑参《白雪歌送武判官归京》", category: .poetry),
            Quote(text: "山回路转不见君，雪上空留马行处。", source: "岑参《白雪歌送武判官归京》", category: .poetry),
            Quote(text: "黄沙百战穿金甲，不破楼兰终不还。", source: "王昌龄《从军行》", category: .poetry),
            Quote(text: "但使龙城飞将在，不教胡马度阴山。", source: "王昌龄《出塞》", category: .poetry),
            Quote(text: "秦时明月汉时关，万里长征人未还。", source: "王昌龄《出塞》", category: .poetry),
            Quote(text: "洛阳亲友如相问，一片冰心在玉壶。", source: "王昌龄《芙蓉楼送辛渐》", category: .poetry),
            Quote(text: "羌笛何须怨杨柳，春风不度玉门关。", source: "王之涣《凉州词》", category: .poetry),
            Quote(text: "欲穷千里目，更上一层楼。", source: "王之涣《登鹳雀楼》", category: .poetry),
            Quote(text: "春风又绿江南岸，明月何时照我还。", source: "王安石《泊船瓜洲》", category: .poetry),
            Quote(text: "不畏浮云遮望眼，自缘身在最高层。", source: "王安石《登飞来峰》", category: .poetry),
            Quote(text: "墙角数枝梅，凌寒独自开。", source: "王安石《梅花》", category: .poetry),
            Quote(text: "遥知不是雪，为有暗香来。", source: "王安石《梅花》", category: .poetry),
            Quote(text: "生当作人杰，死亦为鬼雄。", source: "李清照《夏日绝句》", category: .poetry),
            Quote(text: "至今思项羽，不肯过江东。", source: "李清照《夏日绝句》", category: .poetry),
            Quote(text: "寻寻觅觅，冷冷清清，凄凄惨惨戚戚。", source: "李清照《声声慢》", category: .poetry),
            Quote(text: "这次第，怎一个愁字了得。", source: "李清照《声声慢》", category: .poetry),
            Quote(text: "莫道不消魂，帘卷西风，人比黄花瘦。", source: "李清照《醉花阴》", category: .poetry),
            Quote(text: "知否，知否？应是绿肥红瘦。", source: "李清照《如梦令》", category: .poetry),
            Quote(text: "物是人非事事休，欲语泪先流。", source: "李清照《武陵春》", category: .poetry),
            Quote(text: "只恐双溪舴艋舟，载不动许多愁。", source: "李清照《武陵春》", category: .poetry),
            Quote(text: "花自飘零水自流，一种相思，两处闲愁。", source: "李清照《一剪梅》", category: .poetry),
            Quote(text: "此情无计可消除，才下眉头，却上心头。", source: "李清照《一剪梅》", category: .poetry),
            Quote(text: "昨夜雨疏风骤，浓睡不消残酒。", source: "李清照《如梦令》", category: .poetry),
            Quote(text: "常记溪亭日暮，沉醉不知归路。", source: "李清照《如梦令》", category: .poetry),
            Quote(text: "兴尽晚回舟，误入藕花深处。", source: "李清照《如梦令》", category: .poetry),
            Quote(text: "争渡，争渡，惊起一滩鸥鹭。", source: "李清照《如梦令》", category: .poetry),
            Quote(text: "生当作人杰，死亦为鬼雄。", source: "李清照《夏日绝句》", category: .poetry),
            Quote(text: "至今思项羽，不肯过江东。", source: "李清照《夏日绝句》", category: .poetry),
            Quote(text: "山外青山楼外楼，西湖歌舞几时休？", source: "林升《题临安邸》", category: .poetry),
            Quote(text: "暖风熏得游人醉，直把杭州作汴州。", source: "林升《题临安邸》", category: .poetry),
            Quote(text: "小荷才露尖尖角，早有蜻蜓立上头。", source: "杨万里《小池》", category: .poetry),
            Quote(text: "接天莲叶无穷碧，映日荷花别样红。", source: "杨万里《晓出净慈寺送林子方》", category: .poetry),
            Quote(text: "梅子金黄杏子肥，麦花雪白菜花稀。", source: "范成大《四时田园杂兴》", category: .poetry),
            Quote(text: "儿童急走追黄蝶，飞入菜花无处寻。", source: "杨万里《宿新市徐公店》", category: .poetry),
            Quote(text: "不要人夸好颜色，只留清气满乾坤。", source: "王冕《墨梅》", category: .poetry),
            Quote(text: "粉骨碎身全不怕，要留清白在人间。", source: "于谦《石灰吟》", category: .poetry),
            Quote(text: "千锤万凿出深山，烈火焚烧若等闲。", source: "于谦《石灰吟》", category: .poetry),
            Quote(text: "咬定青山不放松，立根原在破岩中。", source: "郑燮《竹石》", category: .poetry),
            Quote(text: "千磨万击还坚劲，任尔东西南北风。", source: "郑燮《竹石》", category: .poetry),
            Quote(text: "落红不是无情物，化作春泥更护花。", source: "龚自珍《己亥杂诗》", category: .poetry),
            Quote(text: "我劝天公重抖擞，不拘一格降人才。", source: "龚自珍《己亥杂诗》", category: .poetry),
            Quote(text: "九州生气恃风雷，万马齐喑究可哀。", source: "龚自珍《己亥杂诗》", category: .poetry),
            // 补充更多古诗词至300条
            Quote(text: "人生若只如初见，何事秋风悲画扇。", source: "纳兰性德《木兰花令》", category: .poetry),
            Quote(text: "等闲变却故人心，却道故人心易变。", source: "纳兰性德《木兰花令》", category: .poetry),
            Quote(text: "山一程，水一程，身向榆关那畔行，夜深千帐灯。", source: "纳兰性德《长相思》", category: .poetry),
            Quote(text: "风一更，雪一更，聒碎乡心梦不成，故园无此声。", source: "纳兰性德《长相思》", category: .poetry),
            Quote(text: "谁念西风独自凉，萧萧黄叶闭疏窗。", source: "纳兰性德《浣溪沙》", category: .poetry),
            Quote(text: "被酒莫惊春睡重，赌书消得泼茶香，当时只道是寻常。", source: "纳兰性德《浣溪沙》", category: .poetry),
            Quote(text: "一生一代一双人，争教两处销魂。", source: "纳兰性德《画堂春》", category: .poetry),
            Quote(text: "相思相望不相亲，天为谁春。", source: "纳兰性德《画堂春》", category: .poetry),
            Quote(text: "赌书消得泼茶香，当时只道是寻常。", source: "纳兰性德《浣溪沙》", category: .poetry),
            Quote(text: "我是人间惆怅客，知君何事泪纵横。", source: "纳兰性德《浣溪沙》", category: .poetry),
            Quote(text: "明月几时有？把酒问青天。", source: "苏轼《水调歌头》", category: .poetry),
            Quote(text: "不知天上宫阙，今夕是何年。", source: "苏轼《水调歌头》", category: .poetry),
            Quote(text: "我欲乘风归去，又恐琼楼玉宇，高处不胜寒。", source: "苏轼《水调歌头》", category: .poetry),
            Quote(text: "起舞弄清影，何似在人间。", source: "苏轼《水调歌头》", category: .poetry),
            Quote(text: "转朱阁，低绮户，照无眠。", source: "苏轼《水调歌头》", category: .poetry),
            Quote(text: "不应有恨，何事长向别时圆？", source: "苏轼《水调歌头》", category: .poetry),
            Quote(text: "江山如画，一时多少豪杰。", source: "苏轼《念奴娇·赤壁怀古》", category: .poetry),
            Quote(text: "遥想公瑾当年，小乔初嫁了，雄姿英发。", source: "苏轼《念奴娇·赤壁怀古》", category: .poetry),
            Quote(text: "羽扇纶巾，谈笑间，樯橹灰飞烟灭。", source: "苏轼《念奴娇·赤壁怀古》", category: .poetry),
            Quote(text: "故国神游，多情应笑我，早生华发。", source: "苏轼《念奴娇·赤壁怀古》", category: .poetry),
            Quote(text: "人生如梦，一尊还酹江月。", source: "苏轼《念奴娇·赤壁怀古》", category: .poetry),
            Quote(text: "莫听穿林打叶声，何妨吟啸且徐行。", source: "苏轼《定风波》", category: .poetry),
            Quote(text: "竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。", source: "苏轼《定风波》", category: .poetry),
            Quote(text: "料峭春风吹酒醒，微冷，山头斜照却相迎。", source: "苏轼《定风波》", category: .poetry),
            Quote(text: "夜来幽梦忽还乡，小轩窗，正梳妆。", source: "苏轼《江城子》", category: .poetry),
            Quote(text: "相顾无言，惟有泪千行。", source: "苏轼《江城子》", category: .poetry),
            Quote(text: "料得年年肠断处，明月夜，短松冈。", source: "苏轼《江城子》", category: .poetry),
            Quote(text: "会挽雕弓如满月，西北望，射天狼。", source: "苏轼《江城子·密州出猎》", category: .poetry),
            Quote(text: "老夫聊发少年狂，左牵黄，右擎苍。", source: "苏轼《江城子·密州出猎》", category: .poetry),
            Quote(text: "锦帽貂裘，千骑卷平冈。", source: "苏轼《江城子·密州出猎》", category: .poetry),
            Quote(text: "为报倾城随太守，亲射虎，看孙郎。", source: "苏轼《江城子·密州出猎》", category: .poetry),
            Quote(text: "酒酣胸胆尚开张，鬓微霜，又何妨！", source: "苏轼《江城子·密州出猎》", category: .poetry),
            Quote(text: "持节云中，何日遣冯唐？", source: "苏轼《江城子·密州出猎》", category: .poetry),
            Quote(text: "花褪残红青杏小。燕子飞时，绿水人家绕。", source: "苏轼《蝶恋花》", category: .poetry),
            Quote(text: "枝上柳绵吹又少，天涯何处无芳草。", source: "苏轼《蝶恋花》", category: .poetry),
            Quote(text: "墙里秋千墙外道。墙外行人，墙里佳人笑。", source: "苏轼《蝶恋花》", category: .poetry),
            Quote(text: "笑渐不闻声渐悄，多情却被无情恼。", source: "苏轼《蝶恋花》", category: .poetry),
            Quote(text: "春色三分，二分尘土，一分流水。", source: "苏轼《水龙吟》", category: .poetry),
            Quote(text: "细看来，不是杨花，点点是离人泪。", source: "苏轼《水龙吟》", category: .poetry),
            Quote(text: "缺月挂疏桐，漏断人初静。", source: "苏轼《卜算子》", category: .poetry),
            Quote(text: "谁见幽人独往来，缥缈孤鸿影。", source: "苏轼《卜算子》", category: .poetry),
            Quote(text: "惊起却回头，有恨无人省。", source: "苏轼《卜算子》", category: .poetry),
            Quote(text: "拣尽寒枝不肯栖，寂寞沙洲冷。", source: "苏轼《卜算子》", category: .poetry),
            Quote(text: "春宵一刻值千金，花有清香月有阴。", source: "苏轼《春宵》", category: .poetry),
            Quote(text: "歌管楼台声细细，秋千院落夜沉沉。", source: "苏轼《春宵》", category: .poetry),
            Quote(text: "横看成岭侧成峰，远近高低各不同。", source: "苏轼《题西林壁》", category: .poetry),
            Quote(text: "水光潋滟晴方好，山色空蒙雨亦奇。", source: "苏轼《饮湖上初晴后雨》", category: .poetry),
            Quote(text: "蒌蒿满地芦芽短，正是河豚欲上时。", source: "苏轼《惠崇春江晚景》", category: .poetry),
            Quote(text: "黑云翻墨未遮山，白雨跳珠乱入船。", source: "苏轼《六月二十七日望湖楼醉书》", category: .poetry),
            Quote(text: "卷地风来忽吹散，望湖楼下水如天。", source: "苏轼《六月二十七日望湖楼醉书》", category: .poetry),
            Quote(text: "荷尽已无擎雨盖，菊残犹有傲霜枝。", source: "苏轼《赠刘景文》", category: .poetry),
            Quote(text: "一年好景君须记，最是橙黄橘绿时。", source: "苏轼《赠刘景文》", category: .poetry),
            Quote(text: "东风袅袅泛崇光，香雾空蒙月转廊。", source: "苏轼《海棠》", category: .poetry),
            Quote(text: "只恐夜深花睡去，故烧高烛照红妆。", source: "苏轼《海棠》", category: .poetry),
            Quote(text: "梨花淡白柳深青，柳絮飞时花满城。", source: "苏轼《东栏梨花》", category: .poetry),
            Quote(text: "惆怅东栏一株雪，人生看得几清明。", source: "苏轼《东栏梨花》", category: .poetry),
            Quote(text: "林断山明竹隐墙，乱蝉衰草小池塘。", source: "苏轼《鹧鸪天》", category: .poetry),
            Quote(text: "翻空白鸟时时见，照水红蕖细细香。", source: "苏轼《鹧鸪天》", category: .poetry),
            Quote(text: "村舍外，古城旁，杖藜徐步转斜阳。", source: "苏轼《鹧鸪天》", category: .poetry),
            Quote(text: "殷勤昨夜三更雨，又得浮生一日凉。", source: "苏轼《鹧鸪天》", category: .poetry),
            Quote(text: "一别都门三改火，天涯踏尽红尘。", source: "苏轼《临江仙》", category: .poetry),
            Quote(text: "依然一笑作春温。无波真古井，有节是秋筠。", source: "苏轼《临江仙》", category: .poetry),
            Quote(text: "惆怅孤帆连夜发，送行淡月微云。", source: "苏轼《临江仙》", category: .poetry),
            Quote(text: "尊前不用翠眉颦。人生如逆旅，我亦是行人。", source: "苏轼《临江仙》", category: .poetry),
            Quote(text: "夜饮东坡醒复醉，归来仿佛三更。", source: "苏轼《临江仙》", category: .poetry),
            Quote(text: "家童鼻息已雷鸣。敲门都不应，倚杖听江声。", source: "苏轼《临江仙》", category: .poetry),
            Quote(text: "长恨此身非我有，何时忘却营营。", source: "苏轼《临江仙》", category: .poetry),
            Quote(text: "夜阑风静縠纹平。小舟从此逝，江海寄余生。", source: "苏轼《临江仙》", category: .poetry),
            Quote(text: "世事一场大梦，人生几度秋凉。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "夜来风叶已鸣廊。看取眉头鬓上。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "酒贱常愁客少，月明多被云妨。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "中秋谁与共孤光。把盏凄然北望。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "照野弥弥浅浪，横空隐隐层霄。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "障泥未解玉骢骄，我欲醉眠芳草。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "可惜一溪风月，莫教踏碎琼瑶。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "解鞍欹枕绿杨桥，杜宇一声春晓。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "三过平山堂下，半生弹指声中。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "十年不见老仙翁，壁上龙蛇飞动。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "欲吊文章太守，仍歌杨柳春风。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "休言万事转头空，未转头时皆梦。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "点点楼头细雨，重重江外平湖。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "当年戏马会东徐，今日凄凉南浦。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "莫恨黄花未吐，且教红粉相扶。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "酒阑不必看茱萸，俯仰人间今古。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "玉骨那愁瘴雾，冰姿自有仙风。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "海仙时遣探芳丛。倒挂绿毛幺凤。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "素面翻嫌粉涴，洗妆不褪唇红。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "高情已逐晓云空。不与梨花同梦。", source: "苏轼《西江月》", category: .poetry),
            Quote(text: "春未老，风细柳斜斜。", source: "苏轼《望江南》", category: .poetry),
            Quote(text: "试上超然台上看，半壕春水一城花。", source: "苏轼《望江南》", category: .poetry),
            Quote(text: "烟雨暗千家。", source: "苏轼《望江南》", category: .poetry),
            Quote(text: "寒食后，酒醒却咨嗟。", source: "苏轼《望江南》", category: .poetry),
            Quote(text: "休对故人思故国，且将新火试新茶。", source: "苏轼《望江南》", category: .poetry),
            Quote(text: "诗酒趁年华。", source: "苏轼《望江南》", category: .poetry),
            Quote(text: "凤凰山下雨初晴，水风清，晚霞明。", source: "苏轼《江城子》", category: .poetry),
            Quote(text: "一朵芙蕖，开过尚盈盈。", source: "苏轼《江城子》", category: .poetry),
            Quote(text: "何处飞来双白鹭，如有意，慕娉婷。", source: "苏轼《江城子》", category: .poetry),
            Quote(text: "忽闻江上弄哀筝，苦含情，遣谁听！", source: "苏轼《江城子》", category: .poetry),
            Quote(text: "烟敛云收，依约是湘灵。", source: "苏轼《江城子》", category: .poetry),
            Quote(text: "欲待曲终寻问取，人不见，数峰青。", source: "苏轼《江城子》", category: .poetry),
        ]
    }
    
    // 日本哲语（带原文）
    private static var extendedJapaneseQuotes: [Quote] {
        [
            Quote(text: "一期一会。", source: "日本茶道", category: .philosophy, originalText: "一期一会 (Ichigo ichie)", originalLanguage: "ja"),
            Quote(text: "物哀之美。", source: "日本美学", category: .philosophy, originalText: "物の哀れ (Mono no aware)", originalLanguage: "ja"),
            Quote(text: "七次跌倒，八次站起。", source: "日本谚语", category: .motivation, originalText: "七転び八起き (Nana korobi ya oki)", originalLanguage: "ja"),
            Quote(text: "花开花落，皆有时节。", source: "《徒然草》", category: .philosophy, originalText: "花は盛りに (Hana wa sakari ni)", originalLanguage: "ja"),
            Quote(text: "侘寂之美，残缺中的完美。", source: "日本美学", category: .philosophy, originalText: "侘寂 (Wabi-sabi)", originalLanguage: "ja"),
            Quote(text: "樱花飘落的速度是每秒五厘米。", source: "新海诚", category: .poetry, originalText: "桜の花びらの落ちる速度は秒速5センチメートル", originalLanguage: "ja"),
            Quote(text: "人生如樱花，短暂而美丽。", source: "日本谚语", category: .philosophy, originalText: "人生は桜のように短くて美しい", originalLanguage: "ja"),
            Quote(text: "即使跌倒也要向前。", source: "日本谚语", category: .motivation, originalText: "転んでもただでは起きない", originalLanguage: "ja"),
            Quote(text: "水滴石穿。", source: "日本谚语", category: .philosophy, originalText: "雨垂れ石を穿つ", originalLanguage: "ja"),
            Quote(text: "三人行必有我师。", source: "日本谚语", category: .philosophy, originalText: "三人寄れば文殊の知恵", originalLanguage: "ja"),
            Quote(text: "积少成多。", source: "日本谚语", category: .philosophy, originalText: "塵も積もれば山となる", originalLanguage: "ja"),
            Quote(text: "失败是成功之母。", source: "日本谚语", category: .motivation, originalText: "失敗は成功の母", originalLanguage: "ja"),
            Quote(text: "千里之行始于足下。", source: "日本谚语", category: .motivation, originalText: "千里の道も一歩から", originalLanguage: "ja"),
            Quote(text: "时间就是金钱。", source: "日本谚语", category: .time, originalText: "時は金なり", originalLanguage: "ja"),
            Quote(text: "光阴似箭。", source: "日本谚语", category: .time, originalText: "光陰矢の如し", originalLanguage: "ja"),
            Quote(text: "一寸光阴一寸金。", source: "日本谚语", category: .time, originalText: "一寸の光陰一寸の金", originalLanguage: "ja"),
            Quote(text: "知足常乐。", source: "日本谚语", category: .life, originalText: "足るを知る者は常に楽しい", originalLanguage: "ja"),
            Quote(text: "静水流深。", source: "日本谚语", category: .philosophy, originalText: "静かな水は深く流れる", originalLanguage: "ja"),
            Quote(text: "一石二鸟。", source: "日本谚语", category: .philosophy, originalText: "一石二鳥", originalLanguage: "ja"),
            Quote(text: "百闻不如一见。", source: "日本谚语", category: .philosophy, originalText: "百聞は一見に如かず", originalLanguage: "ja"),
            Quote(text: "不忘初心，方得始终。", source: "日本谚语", category: .philosophy, originalText: "初心忘るべからず", originalLanguage: "ja"),
            Quote(text: "滴水穿石。", source: "日本谚语", category: .philosophy, originalText: "雨だれ石を穿つ", originalLanguage: "ja"),
            Quote(text: "良药苦口。", source: "日本谚语", category: .philosophy, originalText: "良薬は口に苦し", originalLanguage: "ja"),
            Quote(text: "塞翁失马，焉知非福。", source: "日本谚语", category: .philosophy, originalText: "塞翁が馬", originalLanguage: "ja"),
            Quote(text: "温故知新。", source: "日本谚语", category: .philosophy, originalText: "温故知新", originalLanguage: "ja"),
            Quote(text: "有志者事竟成。", source: "日本谚语", category: .motivation, originalText: "志ある者は事ついに成る", originalLanguage: "ja"),
            Quote(text: "活到老，学到老。", source: "日本谚语", category: .philosophy, originalText: "六十の手習い", originalLanguage: "ja"),
            Quote(text: "沉默是金。", source: "日本谚语", category: .philosophy, originalText: "沈黙は金", originalLanguage: "ja"),
            Quote(text: "欲速则不达。", source: "日本谚语", category: .philosophy, originalText: "急がば回れ", originalLanguage: "ja"),
            Quote(text: "不入虎穴，焉得虎子。", source: "日本谚语", category: .motivation, originalText: "虎穴に入らずんば虎子を得ず", originalLanguage: "ja"),
            Quote(text: "知者不言，言者不知。", source: "日本谚语", category: .philosophy, originalText: "知る者は言わず、言う者は知らず", originalLanguage: "ja"),
            Quote(text: "人生如逆旅，我亦是行人。", source: "日本谚语", category: .philosophy, originalText: "人生は逆旅、我もまた行人", originalLanguage: "ja"),
            Quote(text: "山不在高，有仙则名。", source: "日本谚语", category: .philosophy, originalText: "山は高さにあらず、仙あれば名あり", originalLanguage: "ja"),
            Quote(text: "路漫漫其修远兮，吾将上下而求索。", source: "日本谚语", category: .motivation, originalText: "道は遠く、我は上下に求索す", originalLanguage: "ja"),
            Quote(text: "岁月不待人。", source: "日本谚语", category: .time, originalText: "歳月人を待たず", originalLanguage: "ja"),
            Quote(text: "一寸光阴一寸金，寸金难买寸光阴。", source: "日本谚语", category: .time, originalText: "一寸の光陰一寸の金、寸金もって寸光陰を買うべからず", originalLanguage: "ja"),
            Quote(text: "明日复明日，明日何其多。", source: "日本谚语", category: .time, originalText: "明日また明日、明日はいくつあるか", originalLanguage: "ja"),
            Quote(text: "少壮不努力，老大徒伤悲。", source: "日本谚语", category: .motivation, originalText: "若い時努力せず、老いて徒らに悲しむ", originalLanguage: "ja"),
            Quote(text: "黑发不知勤学早，白首方悔读书迟。", source: "日本谚语", category: .motivation, originalText: "黒髪は勤学の早さを知らず、白首にして初めて読書の遅さを悔いる", originalLanguage: "ja"),
            Quote(text: "书山有路勤为径，学海无涯苦作舟。", source: "日本谚语", category: .motivation, originalText: "書山に路あり勤を径とし、学海に涯なし苦を舟となす", originalLanguage: "ja"),
            Quote(text: "读万卷书，行万里路。", source: "日本谚语", category: .philosophy, originalText: "万巻の書を読み、万里の路を行く", originalLanguage: "ja"),
            Quote(text: "学而时习之，不亦说乎？", source: "日本谚语", category: .philosophy, originalText: "学びて時に之を習う、また説ばしからずや", originalLanguage: "ja"),
            Quote(text: "三人行，必有我师焉。", source: "日本谚语", category: .philosophy, originalText: "三人行けば、必ず我が師あり", originalLanguage: "ja"),
            Quote(text: "敏而好学，不耻下问。", source: "日本谚语", category: .philosophy, originalText: "敏にして好学、下問を恥じず", originalLanguage: "ja"),
            Quote(text: "学而不思则罔，思而不学则殆。", source: "日本谚语", category: .philosophy, originalText: "学びて思わざれば則ち罔し、思いて学ばざれば則ち殆し", originalLanguage: "ja"),
            Quote(text: "知之为知之，不知为不知，是知也。", source: "日本谚语", category: .philosophy, originalText: "知るを之を知るとし、知らざるを之を知らずとせよ、是れ知るなり", originalLanguage: "ja"),
            Quote(text: "己所不欲，勿施于人。", source: "日本谚语", category: .philosophy, originalText: "己の欲せざる所、人に施すこと勿れ", originalLanguage: "ja"),
            Quote(text: "有朋自远方来，不亦乐乎？", source: "日本谚语", category: .life, originalText: "朋あり遠方より来る、また楽しからずや", originalLanguage: "ja"),
            Quote(text: "工欲善其事，必先利其器。", source: "日本谚语", category: .philosophy, originalText: "工は其の事を善くせんと欲すれば、必ず先ず其の器を利く", originalLanguage: "ja"),
            Quote(text: "人无远虑，必有近忧。", source: "日本谚语", category: .philosophy, originalText: "人遠慮なければ、必ず近憂あり", originalLanguage: "ja"),
            Quote(text: "岁寒，然后知松柏之后凋也。", source: "日本谚语", category: .philosophy, originalText: "歳寒くして、然る後に松柏の後凋を知る", originalLanguage: "ja"),
            Quote(text: "见贤思齐焉，见不贤而内自省也。", source: "日本谚语", category: .philosophy, originalText: "賢を見ては斉しからんとし、不賢を見ては内に自ら省みる", originalLanguage: "ja"),
            Quote(text: "德不孤，必有邻。", source: "日本谚语", category: .philosophy, originalText: "徳は孤ならず、必ず隣あり", originalLanguage: "ja"),
            Quote(text: "君子坦荡荡，小人长戚戚。", source: "日本谚语", category: .philosophy, originalText: "君子は坦蕩蕩、小人は長戚戚", originalLanguage: "ja"),
            Quote(text: "知者乐水，仁者乐山。", source: "日本谚语", category: .philosophy, originalText: "知者は水を楽しみ、仁者は山を楽しむ", originalLanguage: "ja"),
            Quote(text: "不在其位，不谋其政。", source: "日本谚语", category: .philosophy, originalText: "其の位に在らずんば、其の政を謀らず", originalLanguage: "ja"),
            Quote(text: "后生可畏，焉知来者之不如今也？", source: "日本谚语", category: .philosophy, originalText: "後生畏るべし、焉んぞ来者の今に如かざるを知らんや", originalLanguage: "ja"),
            Quote(text: "三军可夺帅也，匹夫不可夺志也。", source: "日本谚语", category: .motivation, originalText: "三軍も帥を奪うべし、匹夫も志を奪うべからず", originalLanguage: "ja"),
            Quote(text: "岁不寒无以知松柏，事不难无以知君子。", source: "日本谚语", category: .philosophy, originalText: "歳寒からざれば松柏を知らず、事難からざれば君子を知らず", originalLanguage: "ja"),
            Quote(text: "不患人之不己知，患不知人也。", source: "日本谚语", category: .philosophy, originalText: "人の己を知らざるを患えず、人を知らざるを患う", originalLanguage: "ja"),
            Quote(text: "学而优则仕，仕而优则学。", source: "日本谚语", category: .philosophy, originalText: "学びて優なれば則ち仕え、仕えて優なれば則ち学ぶ", originalLanguage: "ja"),
            Quote(text: "富与贵，是人之所欲也。", source: "日本谚语", category: .philosophy, originalText: "富と貴とは、人の欲する所なり", originalLanguage: "ja"),
            Quote(text: "贫与贱，是人之所恶也。", source: "日本谚语", category: .philosophy, originalText: "貧と賤とは、人の悪む所なり", originalLanguage: "ja"),
            Quote(text: "不以其道得之，不处也。", source: "日本谚语", category: .philosophy, originalText: "其の道を以て之を得ざれば、処せず", originalLanguage: "ja"),
            Quote(text: "君子喻于义，小人喻于利。", source: "日本谚语", category: .philosophy, originalText: "君子は義に喩え、小人は利に喩える", originalLanguage: "ja"),
            Quote(text: "见利思义，见危授命。", source: "日本谚语", category: .philosophy, originalText: "利を見て義を思い、危を見て命を授く", originalLanguage: "ja"),
            Quote(text: "古之学者为己，今之学者为人。", source: "日本谚语", category: .philosophy, originalText: "古の学者は己の為にし、今の学者は人の為にす", originalLanguage: "ja"),
            Quote(text: "人而无信，不知其可也。", source: "日本谚语", category: .philosophy, originalText: "人にして信なくば、其の可なるを知らず", originalLanguage: "ja"),
            Quote(text: "君子耻其言而过其行。", source: "日本谚语", category: .philosophy, originalText: "君子は其の言の其の行に過ぐるを恥ず", originalLanguage: "ja"),
            Quote(text: "不患无位，患所以立。", source: "日本谚语", category: .philosophy, originalText: "位なきを患えず、立つ所以を患う", originalLanguage: "ja"),
            Quote(text: "不患莫己知，求为可知也。", source: "日本谚语", category: .philosophy, originalText: "己を知る莫きを患えず、知らるべきを求む", originalLanguage: "ja"),
            Quote(text: "君子求诸己，小人求诸人。", source: "日本谚语", category: .philosophy, originalText: "君子は諸を己に求め、小人は諸を人に求む", originalLanguage: "ja"),
            Quote(text: "君子矜而不争，群而不党。", source: "日本谚语", category: .philosophy, originalText: "君子は矜りて争わず、群れて党せず", originalLanguage: "ja"),
            Quote(text: "君子不以言举人，不以人废言。", source: "日本谚语", category: .philosophy, originalText: "君子は言を以て人を挙げず、人を以て言を廃せず", originalLanguage: "ja"),
            Quote(text: "巧言乱德，小不忍则乱大谋。", source: "日本谚语", category: .philosophy, originalText: "巧言は徳を乱し、小忍ばざれば則ち大謀を乱す", originalLanguage: "ja"),
            Quote(text: "人能弘道，非道弘人。", source: "日本谚语", category: .philosophy, originalText: "人は能く道を弘む、道は人を弘むに非ず", originalLanguage: "ja"),
            Quote(text: "过而不改，是谓过矣。", source: "日本谚语", category: .philosophy, originalText: "過ちて改めざる、是れを過ちと謂う", originalLanguage: "ja"),
            Quote(text: "君子有三戒：少之时，血气未定，戒之在色。", source: "日本谚语", category: .philosophy, originalText: "君子に三戒あり：少の時、血気未だ定まらず、色に戒む", originalLanguage: "ja"),
            Quote(text: "及其壮也，血气方刚，戒之在斗。", source: "日本谚语", category: .philosophy, originalText: "其の壮なるに及んで、血気方に剛なり、闘に戒む", originalLanguage: "ja"),
            Quote(text: "及其老也，血气既衰，戒之在得。", source: "日本谚语", category: .philosophy, originalText: "其の老なるに及んで、血気既に衰え、得に戒む", originalLanguage: "ja"),
            Quote(text: "性相近也，习相远也。", source: "日本谚语", category: .philosophy, originalText: "性は相近きなり、習いは相遠きなり", originalLanguage: "ja"),
            Quote(text: "唯上知与下愚不移。", source: "日本谚语", category: .philosophy, originalText: "唯だ上知と下愚とは移らず", originalLanguage: "ja"),
            Quote(text: "恭、宽、信、敏、惠。恭则不侮，宽则得众。", source: "日本谚语", category: .philosophy, originalText: "恭、寬、信、敏、惠。恭なれば則ち侮らず、寬なれば則ち衆を得る", originalLanguage: "ja"),
            Quote(text: "信则人任焉，敏则有功，惠则足以使人。", source: "日本谚语", category: .philosophy, originalText: "信なれば則ち人任ず、敏なれば則ち功あり、惠なれば則ち以て人を使うに足る", originalLanguage: "ja"),
            Quote(text: "人能弘道，非道弘人。", source: "日本谚语", category: .philosophy, originalText: "人は能く道を弘む、道は人を弘むに非ず", originalLanguage: "ja"),
            Quote(text: "道不同，不相为谋。", source: "日本谚语", category: .philosophy, originalText: "道同じからずんば、相謀らず", originalLanguage: "ja"),
            Quote(text: "不患寡而患不均，不患贫而患不安。", source: "日本谚语", category: .philosophy, originalText: "寡なきを患えずして均しからざるを患え、貧しきを患えずして安からざるを患う", originalLanguage: "ja"),
            Quote(text: "既来之，则安之。", source: "日本谚语", category: .philosophy, originalText: "既に来たりたれば、則ち之を安んず", originalLanguage: "ja"),
            Quote(text: "益者三友，损者三友。", source: "日本谚语", category: .philosophy, originalText: "益する者三友あり、損する者三友あり", originalLanguage: "ja"),
            Quote(text: "友直，友谅，友多闻，益矣。", source: "日本谚语", category: .philosophy, originalText: "友は直く、友は諒しく、友は多聞、益なり", originalLanguage: "ja"),
            Quote(text: "友便辟，友善柔，友便佞，损矣。", source: "日本谚语", category: .philosophy, originalText: "友は便辟、友は善柔、友は便佞、損なり", originalLanguage: "ja"),
            Quote(text: "侍于君子有三愆：言未及之而言谓之躁。", source: "日本谚语", category: .philosophy, originalText: "君子に侍るに三愆あり：言未だ之に及ばずして言う、之を躁と謂う", originalLanguage: "ja"),
            Quote(text: "言及之而不言谓之隐，未见颜色而言谓之瞽。", source: "日本谚语", category: .philosophy, originalText: "言之に及んで言わざる、之を隠と謂う、色を見ずして言う、之を瞽と謂う", originalLanguage: "ja"),
            Quote(text: "君子有三戒：少之时，血气未定，戒之在色。", source: "日本谚语", category: .philosophy, originalText: "君子に三戒あり：少の時、血気未だ定まらず、色に戒む", originalLanguage: "ja"),
            Quote(text: "及其壮也，血气方刚，戒之在斗。", source: "日本谚语", category: .philosophy, originalText: "其の壮なるに及んで、血気方に剛なり、闘に戒む", originalLanguage: "ja"),
            Quote(text: "及其老也，血气既衰，戒之在得。", source: "日本谚语", category: .philosophy, originalText: "其の老なるに及んで、血気既に衰え、得に戒む", originalLanguage: "ja"),
            Quote(text: "君子有三畏：畏天命，畏大人，畏圣人之言。", source: "日本谚语", category: .philosophy, originalText: "君子に三畏あり：天命を畏れ、大人を畏れ、聖人の言を畏る", originalLanguage: "ja"),
            Quote(text: "小人不知天命而不畏也，狎大人，侮圣人之言。", source: "日本谚语", category: .philosophy, originalText: "小人は天命を知らずして畏れず、大人を狎れ、聖人の言を侮る", originalLanguage: "ja"),
            Quote(text: "生而知之者，上也；学而知之者，次也。", source: "日本谚语", category: .philosophy, originalText: "生まれながらにして之を知る者は、上なり；学びて之を知る者は、次なり", originalLanguage: "ja"),
            Quote(text: "困而学之，又其次也；困而不学，民斯为下矣。", source: "日本谚语", category: .philosophy, originalText: "困みて之を学ぶ、又其の次なり；困みて学ばざる、民斯れ下と為る", originalLanguage: "ja"),
            Quote(text: "君子有九思：视思明，听思聪，色思温，貌思恭。", source: "日本谚语", category: .philosophy, originalText: "君子に九思あり：視は明を思い、聴は聡を思い、色は温を思い、貌は恭を思う", originalLanguage: "ja"),
            Quote(text: "言思忠，事思敬，疑思问，忿思难，见得思义。", source: "日本谚语", category: .philosophy, originalText: "言は忠を思い、事は敬を思い、疑は問を思い、忿は難を思い、得を見ては義を思う", originalLanguage: "ja"),
            Quote(text: "见善如不及，见不善如探汤。", source: "日本谚语", category: .philosophy, originalText: "善を見ては及ばざるが如く、不善を見ては湯を探るが如し", originalLanguage: "ja"),
            Quote(text: "隐居以求其志，行义以达其道。", source: "日本谚语", category: .philosophy, originalText: "隠居して以て其の志を求め、行義して以て其の道を達す", originalLanguage: "ja"),
            Quote(text: "吾闻其语矣，未见其人也。", source: "日本谚语", category: .philosophy, originalText: "吾其の語を聞く、未だ其の人を見ず", originalLanguage: "ja"),
            Quote(text: "齐景公有马千驷，死之日，民无德而称焉。", source: "日本谚语", category: .philosophy, originalText: "斉の景公に馬千駟あり、死の日、民に徳なくして称する所なし", originalLanguage: "ja"),
            Quote(text: "伯夷、叔齐饿于首阳之下，民到于今称之。", source: "日本谚语", category: .philosophy, originalText: "伯夷、叔斉は首陽の下に餓え、民今に至るまで之を称す", originalLanguage: "ja"),
            Quote(text: "其斯之谓与？", source: "日本谚语", category: .philosophy, originalText: "其れ斯れを之れ謂うか", originalLanguage: "ja"),
            Quote(text: "陈亢问于伯鱼曰：'子亦有异闻乎？'", source: "日本谚语", category: .philosophy, originalText: "陳亢、伯魚に問うて曰く：'子も亦た異聞有りや'", originalLanguage: "ja"),
            Quote(text: "对曰：'未也。尝独立，鲤趋而过庭。'", source: "日本谚语", category: .philosophy, originalText: "対えて曰く：'未だ也。嘗て独立し、鯉趨して庭を過ぐ'", originalLanguage: "ja"),
            Quote(text: "'曰：学诗乎？对曰：未也。'", source: "日本谚语", category: .philosophy, originalText: "'曰く：詩を学ぶか。対えて曰く：未だ也'", originalLanguage: "ja"),
            Quote(text: "'不学诗，无以言。'鲤退而学诗。", source: "日本谚语", category: .philosophy, originalText: "'詩を学ばずんば、以て言う所なし。'鯉退いて詩を学ぶ", originalLanguage: "ja"),
            Quote(text: "他日，又独立，鲤趋而过庭。", source: "日本谚语", category: .philosophy, originalText: "他日、又独立し、鯉趨して庭を過ぐ", originalLanguage: "ja"),
            Quote(text: "'曰：学礼乎？对曰：未也。'", source: "日本谚语", category: .philosophy, originalText: "'曰く：礼を学ぶか。対えて曰く：未だ也'", originalLanguage: "ja"),
            Quote(text: "'不学礼，无以立。'鲤退而学礼。", source: "日本谚语", category: .philosophy, originalText: "'礼を学ばずんば、以て立つ所なし。'鯉退いて礼を学ぶ", originalLanguage: "ja"),
            Quote(text: "闻斯二者。陈亢退而喜曰：'问一得三，闻诗，闻礼，又闻君子之远其子也。'", source: "日本谚语", category: .philosophy, originalText: "斯の二者を聞く。陳亢退いて喜びて曰く：'一を問いて三を得、詩を聞き、礼を聞き、又た君子の其の子を遠ざくるを聞く'", originalLanguage: "ja"),
            Quote(text: "邦君之妻，君称之曰夫人，夫人自称曰小童。", source: "日本谚语", category: .philosophy, originalText: "邦君の妻、君之を称して曰く夫人、夫人自ら称して曰く小童", originalLanguage: "ja"),
            Quote(text: "邦人称之曰君夫人，称诸异邦曰寡小君。", source: "日本谚语", category: .philosophy, originalText: "邦人之を称して曰く君夫人、諸を異邦に称して曰く寡小君", originalLanguage: "ja"),
            Quote(text: "异邦人称之亦曰君夫人。", source: "日本谚语", category: .philosophy, originalText: "異邦人も之を称して亦た曰く君夫人", originalLanguage: "ja"),
        ]
    }
    
    // 欧美名言（带原文）
    private static var extendedWesternQuotes: [Quote] {
        [
            Quote(text: "凡是过往，皆为序章。", source: "莎士比亚", category: .philosophy, originalText: "What's past is prologue.", originalLanguage: "en"),
            Quote(text: "生存还是毁灭，这是一个问题。", source: "莎士比亚", category: .philosophy, originalText: "To be, or not to be, that is the question.", originalLanguage: "en"),
            Quote(text: "我看见，我征服。", source: "凯撒", category: .philosophy, originalText: "I came, I saw, I conquered.", originalLanguage: "en"),
            Quote(text: "时间是最好的老师。", source: "西方谚语", category: .time, originalText: "Time is the best teacher.", originalLanguage: "en"),
            Quote(text: "每一天都是新的开始。", source: "西方谚语", category: .life, originalText: "Every day is a new beginning.", originalLanguage: "en"),
            Quote(text: "生活不是等待暴风雨过去，而是学会在雨中跳舞。", source: "维维安·格林", category: .life, originalText: "Life isn't about waiting for the storm to pass, it's about learning to dance in the rain.", originalLanguage: "en"),
            Quote(text: "世界上最宽阔的是海洋，比海洋更宽阔的是天空，比天空更宽阔的是人的胸怀。", source: "雨果", category: .philosophy, originalText: "L'océan est plus vaste que la terre, le ciel est plus vaste que l'océan, et l'esprit humain est plus vaste que le ciel.", originalLanguage: "fr"),
            Quote(text: "我思故我在。", source: "笛卡尔", category: .philosophy, originalText: "Cogito, ergo sum.", originalLanguage: "la"),
            Quote(text: "把握今天。", source: "贺拉斯", category: .time, originalText: "Carpe diem.", originalLanguage: "la"),
            Quote(text: "艺术永恒，生命短暂。", source: "希波克拉底", category: .philosophy, originalText: "Ars longa, vita brevis.", originalLanguage: "la"),
            Quote(text: "勇者创造命运。", source: "维吉尔", category: .motivation, originalText: "Audentes fortuna iuvat.", originalLanguage: "la"),
            Quote(text: "在怀疑中寻找真理。", source: "古罗马谚语", category: .philosophy, originalText: "In dubio, veritas.", originalLanguage: "la"),
            Quote(text: "知识就是力量。", source: "培根", category: .philosophy, originalText: "Knowledge is power.", originalLanguage: "en"),
            Quote(text: "我唯一知道的就是我一无所知。", source: "苏格拉底", category: .philosophy, originalText: "I know that I know nothing.", originalLanguage: "en"),
            Quote(text: "人是万物的尺度。", source: "普罗泰戈拉", category: .philosophy, originalText: "Man is the measure of all things.", originalLanguage: "en"),
            Quote(text: "给我一个支点，我就能撬动地球。", source: "阿基米德", category: .philosophy, originalText: "Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.", originalLanguage: "en"),
            Quote(text: "人不能两次踏进同一条河流。", source: "赫拉克利特", category: .philosophy, originalText: "No man ever steps in the same river twice.", originalLanguage: "en"),
            Quote(text: "吾爱吾师，吾更爱真理。", source: "亚里士多德", category: .philosophy, originalText: "Plato is dear to me, but dearer still is truth.", originalLanguage: "en"),
            Quote(text: "幸福是人生的最高善。", source: "亚里士多德", category: .philosophy, originalText: "Happiness is the meaning and the purpose of life.", originalLanguage: "en"),
            Quote(text: "存在即合理。", source: "黑格尔", category: .philosophy, originalText: "What is rational is actual and what is actual is rational.", originalLanguage: "en"),
            Quote(text: "人是生而自由的，却无往不在枷锁之中。", source: "卢梭", category: .philosophy, originalText: "Man is born free, and everywhere he is in chains.", originalLanguage: "en"),
            Quote(text: "他人即地狱。", source: "萨特", category: .philosophy, originalText: "Hell is other people.", originalLanguage: "en"),
            Quote(text: "存在先于本质。", source: "萨特", category: .philosophy, originalText: "Existence precedes essence.", originalLanguage: "en"),
            Quote(text: "生活总是让我们遍体鳞伤，但到后来，那些受伤的地方一定会变成我们最强壮的地方。", source: "海明威", category: .life, originalText: "The world breaks everyone, and afterward, many are strong at the broken places.", originalLanguage: "en"),
            Quote(text: "世界上只有一种英雄主义，就是看清生活的真相之后依然热爱生活。", source: "罗曼·罗兰", category: .philosophy, originalText: "There is only one heroism in the world: to see the world as it is and to love it.", originalLanguage: "en"),
            Quote(text: "我来到这个世界，不是为了活着，而是为了生活。", source: "奥斯卡·王尔德", category: .life, originalText: "To live is the rarest thing in the world. Most people just exist.", originalLanguage: "en"),
            Quote(text: "幸福的家庭都是相似的，不幸的家庭各有各的不幸。", source: "托尔斯泰", category: .life, originalText: "Happy families are all alike; every unhappy family is unhappy in its own way.", originalLanguage: "en"),
            Quote(text: "不要因为走得太远，而忘记为什么出发。", source: "纪伯伦", category: .philosophy, originalText: "We already walked too far, down to we had forgotten why embarked.", originalLanguage: "en"),
            Quote(text: "生活是一面镜子，你对它笑，它就对你笑。", source: "萨克雷", category: .life, originalText: "Life is a mirror, if you smile at it, it will smile back at you.", originalLanguage: "en"),
            Quote(text: "生活的理想，就是为了理想的生活。", source: "张闻天", category: .motivation, originalText: "The ideal of life is to live an ideal life.", originalLanguage: "en"),
        ]
    }
    
    // 电影台词
    private static var extendedMovieQuotes: [Quote] {
        [
            Quote(text: "生活就像一盒巧克力，你永远不知道下一颗是什么味道。", source: "《阿甘正传》", category: .life, originalText: "Life is like a box of chocolates, you never know what you're gonna get.", originalLanguage: "en"),
            Quote(text: "希望是美好的，也许是人间至善，而美好的事物永不消逝。", source: "《肖申克的救赎》", category: .philosophy, originalText: "Hope is a good thing, maybe the best of things, and no good thing ever dies.", originalLanguage: "en"),
            Quote(text: "要么忙着活，要么忙着死。", source: "《肖申克的救赎》", category: .life, originalText: "Get busy living, or get busy dying.", originalLanguage: "en"),
            Quote(text: "有些鸟儿是关不住的，它们的每一片羽毛都闪耀着自由的光辉。", source: "《肖申克的救赎》", category: .philosophy, originalText: "Some birds aren't meant to be caged. Their feathers are just too bright.", originalLanguage: "en"),
            Quote(text: "你永远不知道明天和意外哪个先来。", source: "《阿甘正传》", category: .life),
            Quote(text: "死亡是生命的一部分，是我们注定要做的一件事。", source: "《阿甘正传》", category: .philosophy, originalText: "Death is just a part of life, something we're all destined to do.", originalLanguage: "en"),
            Quote(text: "你必须要放下过去，才能继续前进。", source: "《狮子王》", category: .life, originalText: "You have to put your past behind you before you can move on.", originalLanguage: "en"),
            Quote(text: "记住你是谁。", source: "《狮子王》", category: .philosophy, originalText: "Remember who you are.", originalLanguage: "en"),
            Quote(text: "过去可以伤害你，但你可以选择逃避或学习。", source: "《狮子王》", category: .philosophy, originalText: "The past can hurt. But the way I see it, you can either run from it or learn from it.", originalLanguage: "en"),
            Quote(text: "做你自己，因为别人都有人做了。", source: "《成为简·奥斯汀》", category: .philosophy, originalText: "Be yourself, everyone else is already taken.", originalLanguage: "en"),
            Quote(text: "爱是唯一可以超越时间和空间的东西。", source: "《星际穿越》", category: .philosophy, originalText: "Love is the one thing we're capable of perceiving that transcends dimensions of time and space.", originalLanguage: "en"),
            Quote(text: "不要温和地走进那个良夜。", source: "《星际穿越》", category: .philosophy, originalText: "Do not go gentle into that good night.", originalLanguage: "en"),
            Quote(text: "我们曾经仰望星空，思考我们在宇宙中的位置。", source: "《星际穿越》", category: .philosophy, originalText: "We used to look up at the sky and wonder at our place in the stars.", originalLanguage: "en"),
            Quote(text: "时间可以伸缩和折叠，唯独不能倒退。", source: "《星际穿越》", category: .time, originalText: "Time can stretch and it can squeeze, but it can't run backwards.", originalLanguage: "en"),
            Quote(text: "梦想是自由的，但实现梦想需要勇气。", source: "《千与千寻》", category: .motivation, originalText: "夢は自由だ。でも夢を実現するには勇気が必要だ。", originalLanguage: "ja"),
            Quote(text: "曾经发生过的事情不可能忘记，只不过是想不起来而已。", source: "《千与千寻》", category: .philosophy, originalText: "一度あったことは忘れないものさ。思い出せないだけで。", originalLanguage: "ja"),
            Quote(text: "不管前方的路有多苦，只要走的方向正确，不管多么崎岖不平，都比站在原地更接近幸福。", source: "《千与千寻》", category: .life, originalText: "どんなに苦しくても、正しい方向に進んでいれば、どんなに険しくても、その場にいるより幸せに近づける。", originalLanguage: "ja"),
            Quote(text: "人生就是一列开往坟墓的列车，路途上会有很多站，很难有人可以自始至终陪着走完。", source: "《千与千寻》", category: .life, originalText: "人生は墓へ向かう列車のようなもので、途中に多くの駅があり、最初から最後まで一緒にいる人はほとんどいない。", originalLanguage: "ja"),
            Quote(text: "人永远不知道，谁哪次不经意的跟你说了再见之后，就真的不会再见了。", source: "《千与千寻》", category: .life, originalText: "人は永遠に知らない、誰がいつ偶然にさよならを言ったら、本当に二度と会えなくなるのかを。", originalLanguage: "ja"),
            Quote(text: "我只能送你到这里了，剩下的路你要自己走，不要回头。", source: "《千与千寻》", category: .life, originalText: "ここまでしか送れない。あとは自分で歩いて、振り返らないで。", originalLanguage: "ja"),
        ]
    }
    
    // 法语名言
    private static var extendedFrenchQuotes: [Quote] {
        [
            Quote(text: "我思故我在。", source: "笛卡尔", category: .philosophy, originalText: "Je pense, donc je suis.", originalLanguage: "fr"),
            Quote(text: "人是生而自由的，却无往不在枷锁之中。", source: "卢梭", category: .philosophy, originalText: "L'homme est né libre, et partout il est dans les fers.", originalLanguage: "fr"),
            Quote(text: "世界上最宽阔的是海洋，比海洋更宽阔的是天空，比天空更宽阔的是人的胸怀。", source: "雨果", category: .philosophy, originalText: "L'océan est plus vaste que la terre, le ciel est plus vaste que l'océan, et l'esprit humain est plus vaste que le ciel.", originalLanguage: "fr"),
            Quote(text: "生活不是等待暴风雨过去，而是学会在雨中跳舞。", source: "维维安·格林", category: .life, originalText: "La vie n'est pas d'attendre que l'orage passe, mais d'apprendre à danser sous la pluie.", originalLanguage: "fr"),
            Quote(text: "艺术永恒，生命短暂。", source: "希波克拉底", category: .philosophy, originalText: "L'art est long, la vie est courte.", originalLanguage: "fr"),
        ]
    }
    
    // 拉丁语名言
    private static var extendedLatinQuotes: [Quote] {
        [
            Quote(text: "我思故我在。", source: "笛卡尔", category: .philosophy, originalText: "Cogito, ergo sum.", originalLanguage: "la"),
            Quote(text: "把握今天。", source: "贺拉斯", category: .time, originalText: "Carpe diem.", originalLanguage: "la"),
            Quote(text: "艺术永恒，生命短暂。", source: "希波克拉底", category: .philosophy, originalText: "Ars longa, vita brevis.", originalLanguage: "la"),
            Quote(text: "勇者创造命运。", source: "维吉尔", category: .motivation, originalText: "Audentes fortuna iuvat.", originalLanguage: "la"),
            Quote(text: "在怀疑中寻找真理。", source: "古罗马谚语", category: .philosophy, originalText: "In dubio, veritas.", originalLanguage: "la"),
            Quote(text: "知识就是力量。", source: "培根", category: .philosophy, originalText: "Scientia potentia est.", originalLanguage: "la"),
            Quote(text: "时间治愈一切。", source: "古罗马谚语", category: .time, originalText: "Tempus omnia sanat.", originalLanguage: "la"),
            Quote(text: "时间飞逝。", source: "古罗马谚语", category: .time, originalText: "Tempus fugit.", originalLanguage: "la"),
            Quote(text: "人非圣贤，孰能无过。", source: "古罗马谚语", category: .philosophy, originalText: "Errare humanum est.", originalLanguage: "la"),
            Quote(text: "行动胜于雄辩。", source: "古罗马谚语", category: .philosophy, originalText: "Facta, non verba.", originalLanguage: "la"),
        ]
    }
}
